package peerdb

import (
	"context"
	"errors"
	"fmt"
	"log"
	"strconv"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/prometheus/client_golang/prometheus"
)

type PeerDBExporter struct {
	db                 *pgxpool.Pool
	lastAlertTimestamp time.Time

	replicationLag      *prometheus.GaugeVec
	rowsSynced          *prometheus.CounterVec
	rowsSynced24Hours   *prometheus.GaugeVec
	alerts              *prometheus.CounterVec
	flows               *prometheus.GaugeVec
	peers               *prometheus.GaugeVec
	syncThroughput      *prometheus.GaugeVec
	lastSyncTime        *prometheus.GaugeVec
	slotSize            *prometheus.GaugeVec
	batchProcessingTime *prometheus.GaugeVec
	qrepPartitionStatus *prometheus.GaugeVec
	pendingRows         *prometheus.GaugeVec
}

func NewPeerDBExporter(pgpool *pgxpool.Pool) *PeerDBExporter {
	exporter := &PeerDBExporter{
		db: pgpool,
		replicationLag: prometheus.NewGaugeVec(
			prometheus.GaugeOpts{
				Name: "peerdb_replication_lag_seconds",
				Help: "Current replication lag in seconds based on LSN difference",
			},
			[]string{"peer_name", "flow_name"},
		),
		rowsSynced: prometheus.NewCounterVec(
			prometheus.CounterOpts{
				Name: "peerdb_rows_synced_total",
				Help: "Total number of rows synced per table",
			},
			[]string{"batch_id", "flow_name", "table_name"},
		),
		rowsSynced24Hours: prometheus.NewGaugeVec(
			prometheus.GaugeOpts{
				Name: "peerdb_rows_synced_24_hours",
				Help: "Total number of rows synced per table in the last 24 hours",
			},
			[]string{"flow_name", "table_name"},
		),
		alerts: prometheus.NewCounterVec(
			prometheus.CounterOpts{
				Name: "peerdb_alerts",
				Help: "Total number of alerts generated by PeerDB",
			},
			[]string{"alert_key", "alert_level"},
		),
		flows: prometheus.NewGaugeVec(
			prometheus.GaugeOpts{
				Name: "peerdb_flows_details",
				Help: "List of flows and their status",
			},
			[]string{"name", "source_peer", "destination_peer", "status"},
		),
		peers: prometheus.NewGaugeVec(
			prometheus.GaugeOpts{
				Name: "peerdb_peers_status",
				Help: "List of peers and their status",
			},
			[]string{"name", "type"},
		),
		syncThroughput: prometheus.NewGaugeVec(
			prometheus.GaugeOpts{
				Name: "peerdb_sync_throughput_rows_per_second",
				Help: "Sync throughput of the most recent completed batch, in rows per second",
			},
			[]string{"peer_name", "flow_name"},
		),
		lastSyncTime: prometheus.NewGaugeVec(
			prometheus.GaugeOpts{
				Name: "peerdb_last_sync_timestamp_seconds",
				Help: "Timestamp of last successful sync",
			},
			[]string{"peer_name", "flow_name"},
		),
		slotSize: prometheus.NewGaugeVec(
			prometheus.GaugeOpts{
				Name: "peerdb_replication_slot_size_bytes",
				Help: "Size of replication slot indicating lag",
			},
			[]string{"peer_name"},
		),
		batchProcessingTime: prometheus.NewGaugeVec(
			prometheus.GaugeOpts{
				Name: "peerdb_batch_processing_time_seconds",
				Help: "Time taken to process the most recent completed batch",
			},
			[]string{"flow_name"},
		),
		qrepPartitionStatus: prometheus.NewGaugeVec(
			prometheus.GaugeOpts{
				Name: "peerdb_qrep_partition_status",
				Help: "Number of query replication partitions per status (completed/pending)",
			},
			[]string{"peer_name", "flow_name", "status"},
		),
		pendingRows: prometheus.NewGaugeVec(
			prometheus.GaugeOpts{
				Name: "peerdb_pending_rows_total",
				Help: "Number of rows pending sync per table",
			},
			[]string{"peer_name", "flow_name", "table_name"},
		),
	}

	prometheus.MustRegister(
		exporter.replicationLag,
		exporter.rowsSynced,
		exporter.rowsSynced24Hours,
		exporter.alerts,
		exporter.flows,
		exporter.peers,
		exporter.syncThroughput,
		exporter.lastSyncTime,
		exporter.slotSize,
		exporter.batchProcessingTime,
		exporter.qrepPartitionStatus,
		exporter.pendingRows,
	)

	return exporter
}

func (e *PeerDBExporter) collectReplicationMetrics() error {
	query := `
		SELECT 
			flow_name,
			latest_lsn_at_source,
			latest_lsn_at_target
		FROM peerdb_stats.cdc_flows
		WHERE flow_name IS NOT NULL
	`

	rows, err := e.db.Query(context.Background(), query)
	if err != nil {
		return fmt.Errorf("failed to query replication metrics from cdc_flows: %w", err)
	}
	defer rows.Close()

	for rows.Next() {
		var flowName string
		var sourceLSN, targetLSN *int64

		err := rows.Scan(&flowName, &sourceLSN, &targetLSN)
		if err != nil {
			log.Printf("Error scanning replication row: %v", err)
			continue
		}

		// This is only an approximate
		if sourceLSN != nil && targetLSN != nil {
			lag := float64(*sourceLSN - *targetLSN)
			e.replicationLag.WithLabelValues("", flowName).Set(lag)
		}
	}

	return rows.Err()
}

func (e *PeerDBExporter) collectBatchMetrics() error {
	// One row per flow, not one per batch: batch_id is monotonic, so using it as
	// a label creates a new time series for every batch PeerDB ever runs.
	query := `
SELECT DISTINCT ON (flow_name)
    flow_name,
    EXTRACT(EPOCH FROM (end_time - start_time)) as processing_time_seconds,
    rows_in_batch / GREATEST(EXTRACT(EPOCH FROM (end_time - start_time)), 1) as throughput
FROM peerdb_stats.cdc_batches
WHERE end_time IS NOT NULL
ORDER BY flow_name, end_time DESC;
	`

	rows, err := e.db.Query(context.Background(), query)
	if err != nil {
		return fmt.Errorf("failed to query batch metrics: %w", err)
	}
	defer rows.Close()

	for rows.Next() {
		var flowName string
		var processingTime, throughput float64

		err := rows.Scan(&flowName, &processingTime, &throughput)
		if err != nil {
			log.Printf("Error scanning batch row: %v", err)
			continue
		}

		e.batchProcessingTime.WithLabelValues(flowName).Set(processingTime)
		e.syncThroughput.WithLabelValues("", flowName).Set(throughput)
	}

	return rows.Err()
}

func (e *PeerDBExporter) collectSyncedRows24Hours() error {
	// batch_id is only unique within a flow, so cdc_batch_table must be joined on
	// (flow_name, batch_id). Joining on batch_id alone attributes one flow's rows
	// to another and drops flows whose batch ids collide.
	query := `
SELECT
    cbt.flow_name,
    cbt.destination_table_name,
    COALESCE(SUM(cbt.num_rows), 0) AS total_rows
FROM peerdb_stats.cdc_batch_table cbt
JOIN (
    SELECT DISTINCT ON (flow_name, batch_id)
        flow_name,
        batch_id,
        start_time
    FROM peerdb_stats.cdc_batches
    ORDER BY flow_name, batch_id, start_time DESC
) cb ON cb.batch_id = cbt.batch_id AND cb.flow_name = cbt.flow_name
WHERE cb.start_time > NOW() - INTERVAL '24 hours'
GROUP BY cbt.flow_name, cbt.destination_table_name;
	`

	rows, err := e.db.Query(context.Background(), query)
	if err != nil {
		return fmt.Errorf("failed to query table metrics: %w", err)
	}
	defer rows.Close()

	for rows.Next() {
		var flowName, tableName string
		var totalRows int64

		err := rows.Scan(&flowName, &tableName, &totalRows)
		if err != nil {
			log.Printf("Error scanning table metrics row: %v", err)
			continue
		}

		e.rowsSynced24Hours.WithLabelValues(flowName, tableName).Set(float64(totalRows))
	}

	return rows.Err()
}

func (e *PeerDBExporter) collectSlotSizeMetrics() error {
	// Use peer_slot_size for replication slot lag
	query := `
		SELECT 
			peer_name,
			slot_size,
			updated_at
		FROM peerdb_stats.peer_slot_size
		ORDER BY updated_at DESC
	`

	rows, err := e.db.Query(context.Background(), query)
	if err != nil {
		return fmt.Errorf("failed to query slot size metrics: %w", err)
	}
	defer rows.Close()

	for rows.Next() {
		var peerName string
		var slotSize *int64
		var updatedAt time.Time

		err := rows.Scan(&peerName, &slotSize, &updatedAt)
		if err != nil {
			log.Printf("Error scanning slot size row: %v", err)
			continue
		}

		if slotSize != nil {
			e.slotSize.WithLabelValues(peerName).Set(float64(*slotSize))
		}
	}

	return rows.Err()
}

func (e *PeerDBExporter) collectQRepMetrics() error {
	// Aggregated per flow and status. partition_uuid is unique per partition, so
	// exporting it as a label grows the series count without bound.
	query := `
		SELECT 
			flow_name,
			CASE WHEN end_time IS NOT NULL THEN 'completed' ELSE 'pending' END as status,
			COUNT(*) as partition_count,
			COALESCE(SUM(rows_in_partition), 0) as total_rows
		FROM peerdb_stats.qrep_partitions
		GROUP BY flow_name, status
	`

	rows, err := e.db.Query(context.Background(), query)
	if err != nil {
		log.Printf("Warning: Could not query qrep metrics (may not have query replication flows): %v", err)
		return nil
	}
	defer rows.Close()

	for rows.Next() {
		var flowName, status string
		var partitionCount, totalRows int64

		err := rows.Scan(&flowName, &status, &partitionCount, &totalRows)
		if err != nil {
			log.Printf("Error scanning qrep partition row: %v", err)
			continue
		}

		e.qrepPartitionStatus.WithLabelValues("", flowName, status).Set(float64(partitionCount))

		if status == "pending" {
			e.pendingRows.WithLabelValues("", flowName, "qrep_partition").Set(float64(totalRows))
		}
	}

	return rows.Err()
}

func (e *PeerDBExporter) collectAlerts() error {
	// Only read alerts newer than the last one counted. The counter must never
	// be reset, and re-reading the whole table every cycle would double count.
	query := `
		SELECT
			alert_key,
			alert_level,
			created_timestamp
		FROM
			peerdb_stats.alerts_v1
		WHERE created_timestamp > $1
		ORDER BY created_timestamp
	`

	rows, err := e.db.Query(context.Background(), query, e.lastAlertTimestamp)
	if err != nil {
		log.Printf("Warning: Could not load alert errors: %v", err)
		return nil
	}
	defer rows.Close()

	newest := e.lastAlertTimestamp

	for rows.Next() {
		var alertKey, alertLevel string
		var createdTimestamp time.Time

		err := rows.Scan(&alertKey, &alertLevel, &createdTimestamp)
		if err != nil {
			log.Printf("Error scanning for alerts: %v", err)
			return err
		}

		e.alerts.WithLabelValues(alertKey, alertLevel).Inc()

		if createdTimestamp.After(newest) {
			newest = createdTimestamp
		}
	}

	if err := rows.Err(); err != nil {
		return err
	}

	e.lastAlertTimestamp = newest
	return nil
}

func (e *PeerDBExporter) collectPeers() error {
	query := `
		SELECT
			name,
			type
		FROM
			public.peers
	`
	rows, err := e.db.Query(context.Background(), query)
	if err != nil {
		log.Printf("Warning: Could not load peers: %v", err)
		return nil
	}
	defer rows.Close()

	for rows.Next() {
		var name string
		var peerType int

		err := rows.Scan(&name, &peerType)
		if err != nil {
			log.Printf("Error scanning for alerts: %v", err)
			return err
		}

		e.peers.WithLabelValues(name, strconv.Itoa(peerType)).Set(1)
	}
	return rows.Err()
}

func (e *PeerDBExporter) collectFlows() error {
	query := `
		SELECT
			name,
			source_peer,
			destination_peer,
			status
		FROM
			public.flows
	`
	rows, err := e.db.Query(context.Background(), query)
	if err != nil {
		log.Printf("Warning: Could not load flows: %v", err)
		return nil
	}
	defer rows.Close()

	for rows.Next() {
		var name, sourcePeer, destinationPeer string
		var status int

		err := rows.Scan(&name, &sourcePeer, &destinationPeer, &status)
		if err != nil {
			log.Printf("Error scanning for flows: %v", err)
			return err
		}

		e.flows.WithLabelValues(name, sourcePeer, destinationPeer, strconv.Itoa(status)).Set(1)
	}
	return rows.Err()
}

// resetGauges drops every previously exported label set. Each collection cycle
// fully repopulates the gauges from the current query results, so anything not
// re-set is stale (batches that aged out, partitions that finished, flows and
// peers that were deleted) and would otherwise be retained forever.
func (e *PeerDBExporter) resetGauges() {
	e.replicationLag.Reset()
	e.rowsSynced24Hours.Reset()
	e.flows.Reset()
	e.peers.Reset()
	e.syncThroughput.Reset()
	e.lastSyncTime.Reset()
	e.slotSize.Reset()
	e.batchProcessingTime.Reset()
	e.qrepPartitionStatus.Reset()
	e.pendingRows.Reset()
}

func (e *PeerDBExporter) CollectMetrics() error {
	e.resetGauges()

	// Every collector runs even if an earlier one fails. Bailing out early would
	// leave the gauges reset but never repopulated, blanking out unrelated
	// metrics for the rest of the cycle.
	errs := []error{}

	if err := e.collectReplicationMetrics(); err != nil {
		errs = append(errs, fmt.Errorf("failed to collect replication metrics: %w", err))
	}

	if err := e.collectBatchMetrics(); err != nil {
		errs = append(errs, fmt.Errorf("failed to collect batch metrics: %w", err))
	}

	if err := e.collectSyncedRows24Hours(); err != nil {
		errs = append(errs, fmt.Errorf("failed to collect synced rows in 24 hours metrics: %w", err))
	}

	if err := e.collectSlotSizeMetrics(); err != nil {
		errs = append(errs, fmt.Errorf("failed to collect slot size metrics: %w", err))
	}

	if err := e.collectQRepMetrics(); err != nil {
		errs = append(errs, fmt.Errorf("failed to collect QRep metrics: %w", err))
	}

	if err := e.collectFlows(); err != nil {
		errs = append(errs, fmt.Errorf("failed to collect flows: %w", err))
	}

	if err := e.collectAlerts(); err != nil {
		errs = append(errs, fmt.Errorf("failed to collect alerts: %w", err))
	}

	if err := e.collectPeers(); err != nil {
		errs = append(errs, fmt.Errorf("failed to collect peers: %w", err))
	}

	return errors.Join(errs...)
}

func (e *PeerDBExporter) StartMetricsCollection(interval time.Duration) {
	go func() {
		ticker := time.NewTicker(interval)
		defer ticker.Stop()

		if err := e.CollectMetrics(); err != nil {
			log.Printf("Error collecting initial metrics: %v", err)
		}

		for range ticker.C {
			if err := e.CollectMetrics(); err != nil {
				log.Printf("Error collecting metrics: %v", err)
			} else {
				log.Printf("Successfully collected metrics at %v", time.Now())
			}
		}
	}()
}
