name: Build and release Helm chart

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Helm
      uses: azure/setup-helm@v3

    - name: Log in to GitHub Container Registry for Helm
      run: |
        echo ${{ secrets.GH_TOKEN }} | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Extract Helm chart version
      id: chart_version
      run: |
        VERSION=$(grep '^version:' ./charts/peerdb-exporter/Chart.yaml | awk '{print $2}')
        echo "HELM_VERSION=${VERSION}" >> $GITHUB_OUTPUT

    - name: Get previous Helm chart version tag (helm-*)
      id: prevtag
      run: |
        THIS_VERSION=${{ steps.chart_version.outputs.HELM_VERSION }}
        PREVTAG=$(git tag --sort=-creatordate | grep -E '^helm-' | grep -v "helm-${THIS_VERSION}" | tail -n1)
        echo "PREVTAG=$PREVTAG" >> $GITHUB_OUTPUT

    - name: Generate Helm changelog
      id: changelog
      run: |
        if [ -z "${{ steps.prevtag.outputs.PREVTAG }}" ]; then
          RANGE=""
        else
          RANGE="${{ steps.prevtag.outputs.PREVTAG }}..HEAD"
        fi
        git log $RANGE --pretty=format:"* %s" --grep='\[HELM\]$' > CHANGELOG.helm.md
        cat CHANGELOG.helm.md

    - name: Package Helm chart
      run: |
        helm package ./charts/peerdb-exporter 

    - name: Push Helm chart to GHCR
      run: |
        CHART_VERSION=${{ steps.chart_version.outputs.HELM_VERSION }}
        helm push peerdb-exporter-${CHART_VERSION}.tgz oci://ghcr.io/mislavperi

    - name: Create GitHub Release with changelog
      uses: softprops/action-gh-release@v2
      with:
        tag_name: helm-${{ steps.chart_version.outputs.HELM_VERSION }}
        name: Helm Release ${{ steps.chart_version.outputs.HELM_VERSION }}
        body_path: CHANGELOG.helm.md
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
