name: Build and release Docker image

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Extract version from tag
      id: version
      run: |
        TAG_VERSION="${GITHUB_REF#refs/tags/v}"
        echo "DOCKER_VERSION=${TAG_VERSION}" >> $GITHUB_OUTPUT

    - name: Get previous Docker tag
      id: prevtag
      run: |
        PREVTAG=$(git tag --sort=-creatordate | grep '^v' | grep -v "${GITHUB_REF#refs/tags/}" | head -n1)
        echo "PREVTAG=$PREVTAG" >> $GITHUB_OUTPUT

    - name: Generate Docker changelog
      id: changelog
      run: |
        if [ -z "${{ steps.prevtag.outputs.PREVTAG }}" ]; then
          RANGE=""
        else
          RANGE="${{ steps.prevtag.outputs.PREVTAG }}..${GITHUB_REF#refs/tags/}"
        fi
        git log $RANGE --pretty=format:"* %s" --invert-grep --grep='\[HELM\]$' > CHANGELOG.docker.md
        cat CHANGELOG.docker.md

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Build and push Docker image
      run: |
        IMAGE_ID=ghcr.io/mislavperi/peerdb-exporter
        VERSION=${{ steps.version.outputs.DOCKER_VERSION }}
        docker build --build-arg "BUILD_VERSION=${VERSION}" --tag ${IMAGE_ID}:${VERSION} --tag ${IMAGE_ID}:latest .
        docker push ${IMAGE_ID}:${VERSION}
        docker push ${IMAGE_ID}:latest

    - name: Create GitHub Release with changelog
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: Docker Release ${{ steps.version.outputs.DOCKER_VERSION }}
        body_path: CHANGELOG.docker.md
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
